server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edufinity_user?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#config:
#  oauth2:
#    clientid: test1
#    clientSecret: 1234
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      privatekey: -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAx5DVo1kxJMThtfjMyt3sgGdRvmtgtDjfOB29kwqTtTT8FHwo
        tHQaQXaXksmaZv5KMPsdtV8XbOMxdAs6ViYQC/3GyCkim5s7GVKJD8Tk8ibcs29w
        YHjXbupF2XLzrOkECeZXklaOr34i4a2wlCSvUYEeFTzFexdUkrecDU1svIJhxeHI
        Sd0DTQhGJYvIQukIvWpp99Ztd6Ewmi4cYXPDVwAUX4Aj+rViq0iKn0zkAmU2n9DP
        7eswe2I5AFduj3wrQSVICoH6Fqq29Rej/OMnO5l5wxBrJ6lAIcBAlh2bH0XOaidi
        ja0MSdD98IZu7FmfAFd585dauktXdIXG606CEQIDAQABAoIBAGOUk+YElY8hZvdk
        hNwdzOttos5/yitjzY602GnM91OOctLN+YnB/W/4+z1Vt+P4s5CpXXOpVYkR/RVI
        nP1r1MoHAe/TBt/an6zNEHN77joexjYLP2oEIovH/r64q3r2cvt1ovD0nBJZwJIY
        F2p0u77RzO8P+gKn652iXQ4OOln9Wm6CAboK89MYWRMzEl0UDZLIWoiJrCEhIhIg
        paervKzrR4P1dFRuFz1eO/bzYIiH1sxxpOMX2YGbSbSGnDf3gwuO4MC5ZRbFIG4G
        2yx6SWXao4jMD8xX5pMQKL11yxeAfiwMNpox932SVAxpAloyNu7NU9PmmXveI7He
        l/llrJkCgYEA+2cLn09ftoLH/IdES+bS6qy21ALIBooZObW3SBDKl5cMfNrLtxXE
        DfFn/2Zh+RnxKOwj9Nm+2FlSytJ1Y7WOGrRszhq95xtsbpPuxN24VieOEf4PSFgH
        +4ethRYo0kPc/TvHxAUi+FfOLAceRSg97Vw0WfR/VwgNf1FVuPXWsXMCgYEAyzcc
        zO7t+ygQUIrBH/Qjr8InOvRZoGGNQzlNI0C6K9KtVmyqFvzg1OEJydLTl+nYBpdx
        acRFq/5jcuCtmlLA5z1HqyXvtdrlLAg8ctCnaZJkeuwCDhgjQcqyVjB6vNKdHMxI
        RTGoJBNAUmIsUWIgCZ94Mpo7JwuIo5QRrpxSjWsCgYEArcTNCMHBY5LEDq2krF4Q
        vXrCKIr/nV2JEBWlaN+KWPtj+0z0cElQKV8KRkOLRrYCtgl61PxI6JvdGSodT90n
        Kxg4+MENMBgJe+kuqc6jYpGWpqMYByYp5lcivhHSB3w23KacbsYqJMP0UwRcjOrC
        2zTXTrIr7ok3YyBiAyWRzzcCgYAwOSPcfdZ7g0Zb1pF9w7G0Q56LnvCl3oBnM3Ha
        q8GCJLx9hcvXKKsx2TU5b45GvndFGSsQrkLaTcPLvwVzWa/tL92R/66iuQ8pI8s0
        c89GfjbZ9KeIMLItKqynR1nY9SHTc6ayxNXhua/J3QInTeHMZstfNrpSyanjJ4AK
        r43ngQKBgDLQJf+vqjUbhLJb6PaqfSVvyGZ3gD/ws1m0zWs7uJglCbZLIA8OPpIb
        kPIyfjxEU9KmLVq8oKN5667IAtw4VO0sNZpRrkCalIQDsVZTt5oVfgQPnSxiAmUs
        werlk/Kzb+6vxs9PgIiQXTh7tLrWDo1M9H14APljjl2bYSGVe7bh
        -----END RSA PRIVATE KEY-----
      publicKey: -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx5DVo1kxJMThtfjMyt3s
        gGdRvmtgtDjfOB29kwqTtTT8FHwotHQaQXaXksmaZv5KMPsdtV8XbOMxdAs6ViYQ
        C/3GyCkim5s7GVKJD8Tk8ibcs29wYHjXbupF2XLzrOkECeZXklaOr34i4a2wlCSv
        UYEeFTzFexdUkrecDU1svIJhxeHISd0DTQhGJYvIQukIvWpp99Ztd6Ewmi4cYXPD
        VwAUX4Aj+rViq0iKn0zkAmU2n9DP7eswe2I5AFduj3wrQSVICoH6Fqq29Rej/OMn
        O5l5wxBrJ6lAIcBAlh2bH0XOaidija0MSdD98IZu7FmfAFd585dauktXdIXG606C
        EQIDAQAB
        -----END PUBLIC KEY-----